//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Dynamics.Nav.Tools.FormTransformation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Dynamics.Nav.Tools.FormTransformation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should add CaptionML element to this node: {0}.
        /// </summary>
        internal static string AddCaptionMl {
            get {
                return ResourceManager.GetString("AddCaptionMl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some problem with temporary xml file. You can ignore it if no problems with file validation. {0}.
        /// </summary>
        internal static string CanNotDeleteTmpFile {
            get {
                return ResourceManager.GetString("CanNotDeleteTmpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find node {0}. Default {1} will not be applied..
        /// </summary>
        internal static string CanNotFindNode {
            get {
                return ResourceManager.GetString("CanNotFindNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find {0} sub-form ID # {1}.
        /// </summary>
        internal static string CanNotFindSubform {
            get {
                return ResourceManager.GetString("CanNotFindSubform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not possible to get localized caption for {0}{1}:.
        /// </summary>
        internal static string CannotGetMlCaption {
            get {
                return ResourceManager.GetString("CannotGetMlCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find XPos or YPos node.
        /// </summary>
        internal static string CantFindXorY {
            get {
                return ResourceManager.GetString("CantFindXorY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some input file can’t be validated by schema. Please, correct it and rerun tool again.
        /// </summary>
        internal static string CantValidateSchema {
            get {
                return ResourceManager.GetString("CantValidateSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parentless label. Form contains {0} controls which can be recognized as parents for parentless label (id {1}). CaptionML will be copied to first of them. Please, check it manually.
        /// </summary>
        internal static string CheckParentlessLabel {
            get {
                return ResourceManager.GetString("CheckParentlessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandButton {0} will be moved to action group.
        /// </summary>
        internal static string CommandButtonWillBeMovedToActionGroup {
            get {
                return ResourceManager.GetString("CommandButtonWillBeMovedToActionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1}.
        /// </summary>
        internal static string CommentControlRemovalNewLongDescription {
            get {
                return ResourceManager.GetString("CommentControlRemovalNewLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} control &lt;{1}&gt; will be removed..
        /// </summary>
        internal static string ControlWillBeRemoved {
            get {
                return ResourceManager.GetString("ControlWillBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control (ID {0}) with TableRelation and ValidateTableRelation=&apos;No&apos; found..
        /// </summary>
        internal static string ControlWithTableRelationAndValidateTableRelationEqualNo {
            get {
                return ResourceManager.GetString("ControlWithTableRelationAndValidateTableRelationEqualNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save {0}.
        /// </summary>
        internal static string CouldNotSave {
            get {
                return ResourceManager.GetString("CouldNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, change this form&apos;s menu structure. Any form shouldn&apos;t have more than 2 menu levels. This form has at least {0} menu levels. Menu CaptionML: {1}.
        /// </summary>
        internal static string DeepMenuStructure {
            get {
                return ResourceManager.GetString("DeepMenuStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a well formatted XML document..
        /// </summary>
        internal static string FileIsNotAWellFormattedXmlDocument {
            get {
                return ResourceManager.GetString("FileIsNotAWellFormattedXmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load {0}.
        /// </summary>
        internal static string FileLoadError {
            get {
                return ResourceManager.GetString("FileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form {0}: {1}.
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored, due to a {0}.
        /// </summary>
        internal static string FormIgnored {
            get {
                return ResourceManager.GetString("FormIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It’s probably hidden option button. Please correct it somehow..
        /// </summary>
        internal static string HiddenOptionButton {
            get {
                return ResourceManager.GetString("HiddenOptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID in the range for new ID already in use.  Range for new ID is set from {0} to {1} but Id {2} already in use on page {3}!.
        /// </summary>
        internal static string IdAlreadyUsed {
            get {
                return ResourceManager.GetString("IdAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID {0} from the transformation input file, do not exist in the input xml file..
        /// </summary>
        internal static string IDNotFound {
            get {
                return ResourceManager.GetString("IDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing localized strings. .
        /// </summary>
        internal static string ImportingLocalizedStrings {
            get {
                return ResourceManager.GetString("ImportingLocalizedStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect/unsupported encoding page: {0}. For more information regarding encoding page, please, refer to http://msdn.microsoft.com/en-us/library/system.text.encoding.aspx page..
        /// </summary>
        internal static string IncorrectEncodingPage {
            get {
                return ResourceManager.GetString("IncorrectEncodingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language id {0} is incorrect..
        /// </summary>
        internal static string IncorrectLanguageId {
            get {
                return ResourceManager.GetString("IncorrectLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InPage value not set for label ID={0}, CaptionML={1}.
        /// </summary>
        internal static string InPageValueNotSet {
            get {
                return ResourceManager.GetString("InPageValueNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parentless label {0} (&quot;{1}&quot;) was found. If this label should be treated as Instructional Text, please mark it as InstructionalTextML in {2}.
        /// </summary>
        internal static string InstructionalTextSuggestion {
            get {
                return ResourceManager.GetString("InstructionalTextSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatrixLikeLayout: Can&apos;t find control ID {0}. Layout will be generated without this column. Please, add this column manually..
        /// </summary>
        internal static string MatrixLikeLayoutCannotFindControl {
            get {
                return ResourceManager.GetString("MatrixLikeLayoutCannotFindControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge MenuButtons: MenuButton ID# {2} ({3}) will be merged into MenuButton ID# {0} ({1}). These buttons have the same position: {4}..
        /// </summary>
        internal static string MergeMenuButtons {
            get {
                return ResourceManager.GetString("MergeMenuButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one label attached to {0} control (ID {1}) as child. It could be problem with more than one label attached to one control..
        /// </summary>
        internal static string MoreThanOneChild {
            get {
                return ResourceManager.GetString("MoreThanOneChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptionML value ({0}) for control id {1} was moved to variable {2}@{3}. This variable was assigned to CaptionClass property..
        /// </summary>
        internal static string MoveCaptionMLtoCaptionClass {
            get {
                return ResourceManager.GetString("MoveCaptionMLtoCaptionClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /////This functionality was copied from page #{0}. Unsupported part was commented. Please check it.
        ///{{{1}}}
        ///.
        /// </summary>
        internal static string MoveMenuButtonsToSubForm {
            get {
                return ResourceManager.GetString("MoveMenuButtonsToSubForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported by ActionGroup node {0} will be deleted.
        /// </summary>
        internal static string NodeWillBeDeleted {
            get {
                return ResourceManager.GetString("NodeWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label {0}. Parent control doesn&apos;t support ControlType property. Label properties will be ignored..
        /// </summary>
        internal static string ParentControlDoesNotSupportControlTypeProperty {
            get {
                return ResourceManager.GetString("ParentControlDoesNotSupportControlTypeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if parent control property for this label was set correctly or it can be a grouping..
        /// </summary>
        internal static string ParentControlDoesNotSupportControlTypePropertySuggestion {
            get {
                return ResourceManager.GetString("ParentControlDoesNotSupportControlTypePropertySuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label {0}. Parent control is a container. Label properties will be ignored..
        /// </summary>
        internal static string ParentControlIsAController {
            get {
                return ResourceManager.GetString("ParentControlIsAController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if parent control property for this label was set correctly..
        /// </summary>
        internal static string ParentControlIsAControllerSuggestion {
            get {
                return ResourceManager.GetString("ParentControlIsAControllerSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label {0}. Parent control wasn&apos;t set..
        /// </summary>
        internal static string ParentControlNotSet {
            get {
                return ResourceManager.GetString("ParentControlNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label {0}. Parent control property {1} already has assigned value {2}. This value will be changed to label property value: {3}..
        /// </summary>
        internal static string ParentControlPropertyWillBeChangedToLabelProperty {
            get {
                return ResourceManager.GetString("ParentControlPropertyWillBeChangedToLabelProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control with property password has been transformed into a masked text extended data type. This is not a secure solution. If this control is going to be used for entering passwords or other secure data you have to develop a secure solution to support this..
        /// </summary>
        internal static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PictureBox related to Comment Button.
        /// </summary>
        internal static string PictureBoxRelatedToCommentButton {
            get {
                return ResourceManager.GetString("PictureBoxRelatedToCommentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} of.
        /// </summary>
        internal static string PropertyName {
            get {
                return ResourceManager.GetString("PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label {0}. Property {1} will be ignored..
        /// </summary>
        internal static string PropertyWillBeIgnored {
            get {
                return ResourceManager.GetString("PropertyWillBeIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Comment Buttons: CommandButton (ID {0}) and PictureBox controls (ID {1}) will be removed by BitmapList=&apos;7,6&apos;..
        /// </summary>
        internal static string RemoveCommentButton {
            get {
                return ResourceManager.GetString("RemoveCommentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &lt;{0}&gt; will be renamed to &lt;{1}&gt;.
        /// </summary>
        internal static string RenameVariable {
            get {
                return ResourceManager.GetString("RenameVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report {0} already has a request page. Remove it first..
        /// </summary>
        internal static string RequestPageIsAlreadyExists {
            get {
                return ResourceManager.GetString("RequestPageIsAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occurred while transforming form #{0}.
        /// </summary>
        internal static string RunTransformationError {
            get {
                return ResourceManager.GetString("RunTransformationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final actions processing....
        /// </summary>
        internal static string StepActionsFinalProcessing {
            get {
                return ResourceManager.GetString("StepActionsFinalProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add default properties....
        /// </summary>
        internal static string StepAddDefaultProperties {
            get {
                return ResourceManager.GetString("StepAddDefaultProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sorted controls.......
        /// </summary>
        internal static string StepAddSortedControls {
            get {
                return ResourceManager.GetString("StepAddSortedControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligning confirmation dialogs....
        /// </summary>
        internal static string StepAlignConfirmationDialogs {
            get {
                return ResourceManager.GetString("StepAlignConfirmationDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align controls......
        /// </summary>
        internal static string StepAligningControls {
            get {
                return ResourceManager.GetString("StepAligningControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Properties......
        /// </summary>
        internal static string StepCleanProperties {
            get {
                return ResourceManager.GetString("StepCleanProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Trigger Node......
        /// </summary>
        internal static string StepCleanTriggerNode {
            get {
                return ResourceManager.GetString("StepCleanTriggerNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeTransformation......
        /// </summary>
        internal static string StepCodeTransformation {
            get {
                return ResourceManager.GetString("StepCodeTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Bands......
        /// </summary>
        internal static string StepCreateBands {
            get {
                return ResourceManager.GetString("StepCreateBands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create SourceObject......
        /// </summary>
        internal static string StepCreateSourceObject {
            get {
                return ResourceManager.GetString("StepCreateSourceObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Labels....
        /// </summary>
        internal static string StepDeleteLabels {
            get {
                return ResourceManager.GetString("StepDeleteLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize Controls processing.....
        /// </summary>
        internal static string StepFinalizeControlsProcessing {
            get {
                return ResourceManager.GetString("StepFinalizeControlsProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Sorted controls.......
        /// </summary>
        internal static string StepGetSortedControls {
            get {
                return ResourceManager.GetString("StepGetSortedControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log extra information....
        /// </summary>
        internal static string StepLogExtraInformation {
            get {
                return ResourceManager.GetString("StepLogExtraInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Controltype......
        /// </summary>
        internal static string StepManageControlType {
            get {
                return ResourceManager.GetString("StepManageControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage FixedLayout......
        /// </summary>
        internal static string StepManageFixedLayout {
            get {
                return ResourceManager.GetString("StepManageFixedLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Labels......
        /// </summary>
        internal static string StepManageLabels {
            get {
                return ResourceManager.GetString("StepManageLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Option Buttons......
        /// </summary>
        internal static string StepManageOptionButtons {
            get {
                return ResourceManager.GetString("StepManageOptionButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move CommandButtons......
        /// </summary>
        internal static string StepMoveCommandButtons {
            get {
                return ResourceManager.GetString("StepMoveCommandButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Elements From Properties To TriggerNode......
        /// </summary>
        internal static string StepMoveElementsFromPropertiesToTriggerNode {
            get {
                return ResourceManager.GetString("StepMoveElementsFromPropertiesToTriggerNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move MenuButtons......
        /// </summary>
        internal static string StepMoveMenuButtons {
            get {
                return ResourceManager.GetString("StepMoveMenuButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move untouched controls......
        /// </summary>
        internal static string StepMoveUntouchedControls {
            get {
                return ResourceManager.GetString("StepMoveUntouchedControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesting.......
        /// </summary>
        internal static string StepNesting {
            get {
                return ResourceManager.GetString("StepNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Duplicated Menu Button....
        /// </summary>
        internal static string StepRemoveDuplicatedMenuButton {
            get {
                return ResourceManager.GetString("StepRemoveDuplicatedMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unsupported actions......
        /// </summary>
        internal static string StepRemoveUnsupportedActions {
            get {
                return ResourceManager.GetString("StepRemoveUnsupportedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matches found of : {1}.
        /// </summary>
        internal static string SummarizeCodeTransformationAction {
            get {
                return ResourceManager.GetString("SummarizeCodeTransformationAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox as Label found (by {0}). TextBox ID {1} recognized as Label. Source Expression ({2}) moved to CaptionClass of control ID {3}..
        /// </summary>
        internal static string TextBoxAsLabel {
            get {
                return ResourceManager.GetString("TextBoxAsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parent-child relation.
        /// </summary>
        internal static string TextBoxAsLabelByParentChild {
            get {
                return ResourceManager.GetString("TextBoxAsLabelByParentChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X/Y position.
        /// </summary>
        internal static string TextBoxAsLabelByPosition {
            get {
                return ResourceManager.GetString("TextBoxAsLabelByPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width.
        /// </summary>
        internal static string TextBoxAsLabelBywidth {
            get {
                return ResourceManager.GetString("TextBoxAsLabelBywidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox as Label probably found. TextBox ID {0} (Source Expression: {1}) can be recognized as Label. {2} controls can be parent of this control. Please, create correct parent-child relations and run Transformation tool one more time..
        /// </summary>
        internal static string TextBoxAsLabelProbably {
            get {
                return ResourceManager.GetString("TextBoxAsLabelProbably", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Transformation finished {0}. Duration {1} sec ----.
        /// </summary>
        internal static string TransformationFinished {
            get {
                return ResourceManager.GetString("TransformationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------ Transformation started at {0} ------------.
        /// </summary>
        internal static string TransformationStarted {
            get {
                return ResourceManager.GetString("TransformationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger can&apos;t be converted automatically.
        /// </summary>
        internal static string TriggerCanNotBeConvertedAutomatically {
            get {
                return ResourceManager.GetString("TriggerCanNotBeConvertedAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger will be converted automatically. Please check it manually..
        /// </summary>
        internal static string TriggerConvertedAutomatically {
            get {
                return ResourceManager.GetString("TriggerConvertedAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown node &apos;{0}&apos; in {1}.
        /// </summary>
        internal static string UnknownNode {
            get {
                return ResourceManager.GetString("UnknownNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown shortcut &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownShortcut {
            get {
                return ResourceManager.GetString("UnknownShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property or method {0} may not be supported in the RoleTailored client. The following code may not be compiled:
        ///{1}
        ///Analyze your code and add a new rule to the CodeRules.txt file if necessary..
        /// </summary>
        internal static string UnsupportedProperty {
            get {
                return ResourceManager.GetString("UnsupportedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation for {0} failed. Detailed Information: LineNumber={1}, LinePosition={2}.
        /// </summary>
        internal static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
    }
}
